title       = "qqmusic"
baseURL     = "https://qqmusic-cli-cli.tamnd.com/"
description = "Browse QQ Music charts and songs (QQ音乐)"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/qqmusic-cli-cli"
